export interface Product {
  id: string
  name: string
  category: string
  price: number
  image: string
  description: string
  specifications?: Record<string, string>
}

export const products: Product[] = [
  {
    id: 'copper-pipe-3-4',
    name: 'Tubería de cobre 3/4"',
    category: 'Tuberías',
    price: 45.5,
    image: '/images/product-pipes.jpg',
    description:
      'Tubería de cobre de alta calidad para instalaciones de agua potable',
    specifications: {
      Material: 'Cobre tipo L',
      'Diámetro exterior': '0,875"',
      'Diámetro interior': '0,745"',
      Longitud: '3 m (10 ft)',
      Temperatura: '-20 °C a 120 °C',
    },
  },
  {
    id: 'pvc-pipe-2',
    name: 'Tubería PVC 2"',
    category: 'Tuberías',
    price: 12.0,
    image: '/images/product-pipes.jpg',
    description: 'Tubería PVC resistente para desagüe y presión',
    specifications: {
      Material: 'PVC Schedule 40',
      Diámetro: '2"',
      Longitud: '3 m (10 ft)',
      'Presión nominal': '100 PSI',
      Color: 'Blanco',
    },
  },
  {
    id: 'pex-tubing-1-2',
    name: 'Tubo PEX 1/2"',
    category: 'Tuberías',
    price: 0.85,
    image: '/images/product-pipes.jpg',
    description: 'Tubo PEX flexible para distribución de agua',
    specifications: {
      Material: 'Polietileno reticulado (PEX)',
      Diámetro: '1/2"',
      Longitud: '30 cm (1 ft)',
      Temperatura: '-40 °C a 90 °C',
      Presión: '100 PSI',
    },
  },

  {
    id: 'ball-valve-brass-1',
    name: 'Válvula de bola de latón 1"',
    category: 'Válvulas',
    price: 28.75,
    image: '/images/product-valves.jpg',
    description: 'Válvula de bola paso total en latón para agua',
    specifications: {
      Material: 'Cuerpo de latón',
      Diámetro: '1"',
      'Presión nominal': '600 PSI',
      'Rango de temperatura': '-20 °C a 120 °C',
      Conexión: 'Roscada',
    },
  },
  {
    id: 'gate-valve-1-2',
    name: 'Válvula de compuerta 1/2"',
    category: 'Válvulas',
    price: 15.5,
    image: '/images/product-valves.jpg',
    description: 'Válvula de compuerta con asiento resiliente para agua',
    specifications: {
      Material: 'Hierro dúctil',
      Diámetro: '1/2"',
      'Presión nominal': '200 PSI',
      Temperatura: '0 °C a 60 °C',
      Tipo: 'Asiento resiliente',
    },
  },
  {
    id: 'check-valve-1',
    name: 'Válvula de retención 1"',
    category: 'Válvulas',
    price: 22.0,
    image: '/images/product-valves.jpg',
    description: 'Válvula antirretorno con resorte para evitar retornos',
    specifications: {
      Material: 'Latón con resorte inoxidable',
      Diámetro: '1"',
      'Presión nominal': '200 PSI',
      Tipo: 'Con resorte',
      Conexión: 'Roscada',
    },
  },

  {
    id: 'elbow-90-brass-1',
    name: 'Codo 90° de latón 1"',
    category: 'Racores',
    price: 8.5,
    image: '/images/product-fittings.jpg',
    description: 'Codo de 90° en latón para cambios de dirección',
    specifications: {
      Material: 'Latón',
      Ángulo: '90°',
      Diámetro: '1"',
      Conexión: 'Roscada',
      Presión: '600 PSI',
    },
  },
  {
    id: 'tee-connector-3-4',
    name: 'Tee (derivación) 3/4"',
    category: 'Racores',
    price: 6.25,
    image: '/images/product-fittings.jpg',
    description: 'Tee de tres vías para derivaciones en tubería',
    specifications: {
      Material: 'Latón',
      Diámetro: '3/4"',
      Tipo: 'Tee igual',
      Conexión: 'Roscada',
      Presión: '600 PSI',
    },
  },
  {
    id: 'union-connector-1-2',
    name: 'Unión desmontable 1/2"',
    category: 'Racores',
    price: 12.75,
    image: '/images/product-fittings.jpg',
    description: 'Unión rápida desmontable para montaje sencillo',
    specifications: {
      Material: 'Latón',
      Diámetro: '1/2"',
      Tipo: 'Unión',
      Conexión: 'Roscada',
      Presión: '300 PSI',
    },
  },

  {
    id: 'gas-regulator-propane',
    name: 'Regulador de gas propano',
    category: 'Gas',
    price: 65.0,
    image: '/images/product-gas-parts.jpg',
    description: 'Regulador de alta eficiencia para instalaciones a gas',
    specifications: {
      Tipo: 'Regulador propano',
      'Presión entrada': '150–250 PSI',
      'Presión salida': '5–12" c.a.',
      Caudal: '90 CFH máx.',
      Material: 'Aluminio / acero inoxidable',
    },
  },
  {
    id: 'gas-line-1-2-flex',
    name: 'Línea flexible de gas 1/2"',
    category: 'Gas',
    price: 18.5,
    image: '/images/product-gas-parts.jpg',
    description: 'Conector flexible de acero inoxidable para gas',
    specifications: {
      Material: 'Acero inoxidable trenzado',
      Diámetro: '1/2"',
      Longitud: '0,9 m (3 ft)',
      'Presión máxima': '5 PSI',
      Temperatura: '-40 °C a 75 °C',
    },
  },
  {
    id: 'gas-fitting-brass-male',
    name: 'Racor de gas macho latón 1/2"',
    category: 'Gas',
    price: 9.75,
    image: '/images/product-gas-parts.jpg',
    description: 'Racor estándar en latón para conexiones de gas',
    specifications: {
      Material: 'Latón',
      Diámetro: '1/2"',
      Rosca: 'NPT',
      'Presión nominal': '500 PSI',
      Tipo: 'Macho adaptador',
    },
  },

  {
    id: 'water-filter-housing',
    name: 'Carcasa para filtro de agua',
    category: 'Filtros',
    price: 35.0,
    image: '/images/product-pipes.jpg',
    description: 'Carcasa completa para montaje de cartucho filtrante',
    specifications: {
      Material: 'Polipropileno',
      'Tamaño cartucho': '10"',
      Caudal: '15 GPM',
      'Presión nominal': '125 PSI',
      Conexión: '3/4" FPT',
    },
  },
  {
    id: 'pressure-gauge-water',
    name: 'Manómetro de presión de agua',
    category: 'Medidores',
    price: 16.5,
    image: '/images/product-valves.jpg',
    description: 'Manómetro preciso para monitoreo de presión',
    specifications: {
      'Diámetro esfera': '2,5"',
      Rango: '0–100 PSI',
      Precisión: '±3 %',
      Conexión: '1/4" NPT',
      Material: 'Acero inoxidable',
    },
  },
  {
    id: 'shutoff-valve-angle',
    name: 'Llave de paso angular',
    category: 'Válvulas',
    price: 19.5,
    image: '/images/product-valves.jpg',
    description: 'Llave de corte angular para alimentación de artefactos',
    specifications: {
      Material: 'Latón',
      Tamaño: '1/2"',
      Tipo: 'Angular',
      Presión: '125 PSI',
      Manija: 'Metálica',
    },
  },
  {
    id: 'strainer-filter-basket',
    name: 'Colador / filtro en Y 3/4"',
    category: 'Filtros',
    price: 14.0,
    image: '/images/product-fittings.jpg',
    description: 'Colador en Y con cesta filtrante reemplazable',
    specifications: {
      Material: 'Cuerpo de latón',
      Tamaño: '3/4"',
      Malla: '100 micrones',
      Presión: '200 PSI',
      Conexión: 'Roscada',
    },
  },
]
